-- Gerado por scripts/gerar-seed.ts — não editar à mão, editar a fonte em src/lib/motor-fluxo/ e regerar.
-- Rodar no SQL Editor do Supabase depois das migrations 001-004.

-- Entidade legal e unidade de negócio (ArrudaCred)
insert into entidades_legais (id, razao_social, cnpj) values ('35c255fa-469d-40e0-89ae-dcb30eaedb62', 'L.H. DE ARRUDA D. DO VALLE SERVIÇOS LTDA', '40342851000137');
insert into unidades_negocio (id, entidade_legal_id, nome) values ('931a408d-0c7a-4d88-ab07-49a3b46f0eb4', '35c255fa-469d-40e0-89ae-dcb30eaedb62', 'ArrudaCred');

-- Produto
insert into produtos (id, unidade_negocio_id, nome, tipo, fonte_receita) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', '931a408d-0c7a-4d88-ab07-49a3b46f0eb4', 'Limpeza de Nome (CPF/CNPJ) — Serasa/SPC', 'proprio', 'venda_direta');

-- Fluxos
insert into fluxos (id, produto_id, nome) values ('964cb6eb-3613-4db5-b3c0-c1ea47be410a', null, 'Abertura e Triagem');
insert into fluxos (id, produto_id, nome) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 'aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'Atendimento — Limpeza de Nome Serasa/SPC');

-- Etapas do fluxo (o "editor de fluxo" — PLANO_MESTRE seção 8.9)
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('964cb6eb-3613-4db5-b3c0-c1ea47be410a', 1, 'mensagem_sequencial', '{"codigo":"saudacao_inicial","mensagens":[{"tipo":"imagem","midia_url":"","legenda":"Foto da Malala (avatar/mascote — moldura navy/dourado, ver referência visual do script)"},{"tipo":"texto","texto":"🙋‍♂️🙋‍♂️ Olá, eu sou Malala, consultora digital especializada em recuperação e acesso a crédito aqui na ArrudaCred!"}],"aguarda_resposta":false,"proximo_codigo":"pergunta_nome","kanban_subetapa":"novo_lead_triagem"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('964cb6eb-3613-4db5-b3c0-c1ea47be410a', 2, 'pergunta_checkpoint', '{"codigo":"pergunta_nome","mensagens":[{"tipo":"texto","texto":"👉 *Com quem eu falo?*"}],"aguarda_resposta":true,"tipo_resposta":"texto_livre","proximo_codigo":"saudacao_personalizada","kanban_subetapa":"novo_lead_triagem"}'::jsonb, 'nome');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('964cb6eb-3613-4db5-b3c0-c1ea47be410a', 3, 'mensagem_sequencial', '{"codigo":"saudacao_personalizada","mensagens":[{"tipo":"texto","texto":"Oi [Primeiro_Nome], [saudacao]! É um prazer atender você!"}],"aguarda_resposta":false,"proximo_codigo":"abertura_telefone","kanban_subetapa":"novo_lead_triagem"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('964cb6eb-3613-4db5-b3c0-c1ea47be410a', 4, 'pergunta_checkpoint', '{"codigo":"abertura_telefone","mensagens":[{"tipo":"texto","texto":"Pra eu continuar seu atendimento, me confirma um WhatsApp ou telefone de contato:"}],"aguarda_resposta":true,"tipo_resposta":"texto_livre","proximo_codigo":"abertura_email","kanban_subetapa":"novo_lead_triagem"}'::jsonb, 'telefone');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('964cb6eb-3613-4db5-b3c0-c1ea47be410a', 5, 'pergunta_checkpoint', '{"codigo":"abertura_email","mensagens":[{"tipo":"texto","texto":"Para te atender melhor, preciso que me informe o seu e-mail:"}],"aguarda_resposta":true,"tipo_resposta":"email","proximo_codigo":"triagem_menu","kanban_subetapa":"novo_lead_triagem"}'::jsonb, 'email');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('964cb6eb-3613-4db5-b3c0-c1ea47be410a', 6, 'pergunta_checkpoint', '{"codigo":"triagem_menu","mensagens":[{"tipo":"texto","texto":"Para agilizar seu atendimento, informe o número da opção:\n\n1️⃣ Limpeza de Nome (CPF/CNPJ)\n2️⃣ Aumento de Score / Rating\n3️⃣ BACEN / SCR / CCF\n4️⃣ Jusbrasil / Escavador\n5️⃣ Conta Protegida (Bloqueio Judicial)\n6️⃣ Consórcio\n7️⃣ Crédito / Financiamento\n8️⃣ Outro assunto\n\n👉 *É só responder com o número da opção* 😊"}],"aguarda_resposta":true,"tipo_resposta":"menu","opcoes":[{"valor":"limpeza_nome","rotulos":["1","1️⃣"],"proximo_codigo":"ln_passo2"},{"valor":"score","rotulos":["2","2️⃣"],"proximo_codigo":"handoff_humano"},{"valor":"bacen_scr_ccf","rotulos":["3","3️⃣"],"proximo_codigo":"handoff_humano"},{"valor":"jusbrasil_escavador","rotulos":["4","4️⃣"],"proximo_codigo":"handoff_humano"},{"valor":"conta_protegida","rotulos":["5","5️⃣"],"proximo_codigo":"handoff_humano"},{"valor":"consorcio","rotulos":["6","6️⃣"],"proximo_codigo":"handoff_humano"},{"valor":"credito","rotulos":["7","7️⃣"],"proximo_codigo":"handoff_humano"},{"valor":"outro_assunto","rotulos":["8","8️⃣"],"proximo_codigo":"handoff_humano"}],"kanban_subetapa":"novo_lead_triagem"}'::jsonb, 'produto_interesse');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('964cb6eb-3613-4db5-b3c0-c1ea47be410a', 7, 'mensagem_sequencial', '{"codigo":"handoff_humano","mensagens":[{"tipo":"texto","texto":"Perfeito! Esse assunto eu já vou encaminhar direto para um de nossos consultores te ajudar — só um instante 🙋‍♂️"}],"aguarda_resposta":false,"encerramento":{"sob_supervisor":true},"kanban_subetapa":"novo_lead_triagem"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 2, 'pergunta_checkpoint', '{"codigo":"ln_passo2","mensagens":[{"tipo":"texto","texto":"🤔 Se você responder 4 perguntas rápidas, em menos de um minuto eu já consigo informar o valor exato para limpar o seu nome. Depois disso, tiro todas as suas dúvidas e, se preferir, também podemos conversar por ligação.\n\n👉 *Podemos começar?*"}],"aguarda_resposta":true,"tipo_resposta":"sim_nao","opcoes":[{"valor":"sim","rotulos":["sim","s"],"proximo_codigo":"ln_passo3"},{"valor":"nao","rotulos":["nao","n"],"proximo_codigo":"ln_aguardar_melhor_momento"}],"kanban_subetapa":"qualificacao"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 3, 'mensagem_sequencial', '{"codigo":"ln_aguardar_melhor_momento","mensagens":[{"tipo":"texto","texto":"Sem problema! Fico por aqui e retomo com você mais tarde, combinado? 🙂"}],"aguarda_resposta":false,"encerramento":{"sob_supervisor":false},"kanban_subetapa":"qualificacao"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 4, 'mensagem_sequencial', '{"codigo":"ln_passo3","mensagens":[{"tipo":"texto","texto":"✅ A proposta do nosso trabalho é remover as restrições que estão negativando seu CPF ou CNPJ — independentemente da origem: contas não pagas, cartão de crédito, empréstimos, financiamentos, protestos, cheques devolvidos ou ações de cobrança.\n\n👉 O objetivo é que seu nome fique limpo, permitindo que você recupere sua reputação financeira e consiga voltar a pleitear acesso a crédito no mercado."},{"tipo":"texto","texto":"⚖️ O procedimento é realizado por meio de ação judicial coletiva via associação de proteção ao consumidor, garantindo direitos previstos em lei, removendo as restrições no SERASA, SPC Brasil, SCPC Boa Vista e CENPROT (Central Nacional de Protestos).\n\n📌 O serviço conta com seguro-garantia de manutenção do nome limpo pelo período de 1 ANO, conforme condições contratuais (após 12 meses as restrições podem retornar se não forem negociadas ou pagas neste período)."},{"tipo":"texto","texto":"⚠️ Importante entender: RESTRIÇÃO é uma coisa, DÍVIDA é outra! As restrições que hoje estão negativando seu nome nestes orgãos serão 100% removidas. Já as dívidas, continuarão existindo de forma interna no credor e nos sistemas do Banco Central.\n\n✅ Em resumo: uma forma rápida e legal de obter CPF ou CNPJ limpo no sistema Serasa/SPC por um custo menor do que se fosse pagar as dívidas."}],"aguarda_resposta":false,"proximo_codigo":"ln_passo4","kanban_subetapa":"qualificacao"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 5, 'pergunta_checkpoint', '{"codigo":"ln_passo4","mensagens":[{"tipo":"texto","texto":"👉 Você precisa limpar o *CPF* ou *CNPJ*?"}],"aguarda_resposta":true,"tipo_resposta":"menu","opcoes":[{"valor":"cpf","rotulos":["cpf"],"proximo_codigo":"ln_passo5"},{"valor":"cnpj","rotulos":["cnpj"],"proximo_codigo":"ln_passo5"},{"valor":"cpf_e_cnpj","rotulos":["cpf e cnpj","os dois","ambos","cnpj e cpf"],"proximo_codigo":"ln_passo5"}],"kanban_subetapa":"qualificacao"}'::jsonb, 'tipo_documento');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 6, 'mensagem_sequencial', '{"codigo":"ln_passo5","mensagens":[{"tipo":"texto","texto":"Ótimo! Podemos auxiliar sim com o processo limpa nome."}],"aguarda_resposta":false,"proximo_codigo":"ln_passo6","kanban_subetapa":"qualificacao"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 7, 'pergunta_checkpoint', '{"codigo":"ln_passo6","mensagens":[{"tipo":"texto","texto":"👉 *Em qual das faixas abaixo melhor se enquadra o valor das restrições neste CPF atualmente?* (tudo bem se não tiver certeza - depois faremos uma consulta)\n\n1️⃣ Menos de 10 mil\n2️⃣ Entre 10 e 30 mil\n3️⃣ Entre 30 e 50 mil\n4️⃣ Entre 50 e 100 mil\n5️⃣ Mais de 100 mil"}],"aguarda_resposta":true,"tipo_resposta":"menu","opcoes":[{"valor":"menos_10mil","rotulos":["1","1️⃣"],"proximo_codigo":"ln_passo6_refino_baixo"},{"valor":"10_30mil","rotulos":["2","2️⃣"],"proximo_codigo":"ln_passo8"},{"valor":"30_50mil","rotulos":["3","3️⃣"],"proximo_codigo":"ln_passo8"},{"valor":"50_100mil","rotulos":["4","4️⃣"],"proximo_codigo":"ln_passo8"},{"valor":"mais_100mil","rotulos":["5","5️⃣"],"proximo_codigo":"ln_passo6_refino_alto"}],"kanban_subetapa":"faixa_divida"}'::jsonb, 'faixa_valor');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 8, 'pergunta_checkpoint', '{"codigo":"ln_passo6_refino_baixo","mensagens":[{"tipo":"texto","texto":"Entendo, para eu conseguir te orientar melhor me responda:\n\n1️⃣ Menos de 3 Mil\n2️⃣ Entre 3 e 10 Mil"}],"aguarda_resposta":true,"tipo_resposta":"menu","opcoes":[{"valor":"menos_3mil","rotulos":["1","1️⃣"],"proximo_codigo":"ln_passo7"},{"valor":"3_10mil","rotulos":["2","2️⃣"],"proximo_codigo":"ln_passo8"}],"kanban_subetapa":"faixa_divida"}'::jsonb, 'faixa_valor_detalhe');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 9, 'pergunta_checkpoint', '{"codigo":"ln_passo6_refino_alto","mensagens":[{"tipo":"texto","texto":"Entendi que são mais de 100 mil reais, para eu conseguir te orientar melhor, preciso que me informe o valor aproximado das restrições - pode escrever... (tudo bem se não tiver certeza - depois faremos uma consulta)"}],"aguarda_resposta":true,"tipo_resposta":"numero_ou_nao_sei","proximo_codigo":"ln_passo8","kanban_subetapa":"faixa_divida","interpretacao_ia":{"habilitado":true,"instrucao":"O lead pode responder o valor aproximado da restrição de forma bem livre (por extenso, com gírias, faixa vaga tipo ''uns 200 e pouco''). Extraia um número em reais o mais próximo possível do que ele quis dizer."}}'::jsonb, 'valor_aproximado');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 10, 'pergunta_checkpoint', '{"codigo":"ln_passo7","mensagens":[{"tipo":"texto","texto":"😊 Aqui na ArrudaCred nós sempre buscamos orientar o cliente da forma que entendemos ser mais vantajosa para ele.\n\nComo o valor total das restrições é inferior a R$ 3.000, vale a pena considerar que nosso serviço de limpeza de nome tem um investimento mínimo de R$ 899 à vista ou 6x de R$ 299. Além disso, é importante lembrar que as dívidas continuam existindo, ou seja, a ação remove as restrições, mas não quita os débitos.\n\nPor isso, nesse cenário, nossa recomendação é que você avalie a possibilidade de negociar e quitar diretamente essas dívidas, pois, financeiramente, essa costuma ser a opção mais vantajosa.\n\nSe, ainda assim, você preferir seguir com a ação para remover as restrições do seu nome, será um prazer ajudar. Podemos continuar?"}],"aguarda_resposta":true,"tipo_resposta":"sim_nao","opcoes":[{"valor":"sim","rotulos":["sim","s"],"proximo_codigo":"ln_passo8"},{"valor":"nao","rotulos":["nao","n"],"encerra_com_perda":true,"motivo_perda":"LEAD OPTOU POR NEGOCIAR DÍVIDA DIRETAMENTE"}],"kanban_subetapa":"faixa_divida"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 11, 'condicional', '{"codigo":"ln_passo8","mensagens":[{"tipo":"texto","texto":"👍 Entendido! Me conta: você já contratou algum serviço de limpeza de nome antes? E como conheceu a ArrudaCred? Foi indicação de alguém? 🤔"}],"aguarda_resposta":true,"tipo_resposta":"texto_livre","proximo_condicional":{"contem_qualquer":["google","internet","site","instagram","facebook","busca","pesquis"],"se_sim":"ln_passo9","se_nao":"ln_passo10"},"kanban_subetapa":"faixa_divida"}'::jsonb, 'experiencia_e_origem');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 12, 'mensagem_sequencial', '{"codigo":"ln_passo9","mensagens":[{"tipo":"texto","texto":"Obrigado por nos informar, estamos bem posicionados nos mecanismos de busca justamente por conta da nossa reputação e boa avaliação de clientes que já nos contrataram..."}],"aguarda_resposta":false,"proximo_codigo":"ln_passo10","kanban_subetapa":"faixa_divida"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 13, 'mensagem_sequencial', '{"codigo":"ln_passo10","mensagens":[{"tipo":"texto","texto":"Pergunto porque para nós a relação com nossos clientes vale mais que uma venda isolada, assim ganhamos indicações com a confiança estabelecida. Entendemos a preocupação de quem ainda não nos conhece e tem medo de cair num golpe ou na mão de gente desonesta..."}],"aguarda_resposta":false,"proximo_codigo":"ln_passo11","kanban_subetapa":"faixa_divida"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 14, 'mensagem_sequencial', '{"codigo":"ln_passo11","mensagens":[{"tipo":"texto","texto":"⭐⭐⭐⭐⭐\nSomos uma empresa com 5 anos de atuação no mercado de recuperação de crédito, trabalhando sempre com contrato para prestação de serviços, que deixa claro os direitos e deveres tanto do cliente quanto da empresa.\n\n👉 *Não existe milagre. O que existe é processo dentro da lei, contrato, prazo e compromisso.*\n👉 No último ano, auxiliamos mais de 5 mil clientes em processos de regularização de crédito.\n👉 Atualmente temos avaliação 4,9 no Google (o máximo é nota 5,0) e avaliação 9,5 no Reclame Aqui (máximo é nota 10)."},{"tipo":"texto","texto":"📌 Dados da empresa:\nARRUDACRED – HUB ARRUDA DE NEGÓCIOS E SERVIÇOS\nL.H. DE ARRUDA D. DO VALLE SERVIÇOS LTDA\nCNPJ: 40.342.851/0001-37\n\n🌐 Site: https://www.arrudacred.com.br\n\n📷 Instagram:\nhttps://instagram.com/arrudacred.br\n\n*Trabalhamos com foco em transparência e segurança para o cliente, oferecendo*:\n\n✅ Contrato de prestação de serviços\n✅ Google com avaliação 5 estrelas\n✅ Reclame Aqui com avaliação 9,5 (ótima)\n✅ Mais de 5 mil clientes atendidos\n✅ Seguro Garantia de 12 meses incluso"},{"tipo":"imagem","midia_url":"","legenda":"Selo do Prêmio Reclame Aqui 2026 (círculo verde escuro, \"Melhores empresas para o consumidor 2026\")"},{"tipo":"texto","texto":"A *ARRUDACRED* está concorrendo ao *Prêmio Reclame AQUI*. Nossa empresa foi indicada na categoria RECUPERAÇÃO DE CRÉDITO, junto de outras grandes no segmento, como CENPROT NACIONAL E SPC BRASIL.\n\nVeja você mesmo:\n📌 https://www.reclameaqui.com.br/premio/classificadas-indicadas/financeiras/"}],"aguarda_resposta":false,"proximo_codigo":"ln_passo12","kanban_subetapa":"faixa_divida"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 15, 'pergunta_checkpoint', '{"codigo":"ln_passo12","mensagens":[{"tipo":"texto","texto":"📣 *Para eu conseguir te orientar melhor me diz: para quando você tem necessidade do CPF limpo?*\n\n1️⃣ Só está pesquisando\n2️⃣ Urgente\n3️⃣ Em 30-45 dias\n4️⃣ 3 a 6 meses\n5️⃣ Outro, me explique!"}],"aguarda_resposta":true,"tipo_resposta":"menu","opcoes":[{"valor":"pesquisando","rotulos":["1","1️⃣"],"proximo_codigo":"ln_passo13"},{"valor":"urgente","rotulos":["2","2️⃣"],"proximo_codigo":"ln_passo13"},{"valor":"30_45_dias","rotulos":["3","3️⃣"],"proximo_codigo":"ln_passo13"},{"valor":"3_6_meses","rotulos":["4","4️⃣"],"proximo_codigo":"ln_passo13"},{"valor":"outro","rotulos":["5","5️⃣"],"proximo_codigo":"ln_passo12_explique"}],"kanban_subetapa":"faixa_divida"}'::jsonb, 'urgencia');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 16, 'pergunta_checkpoint', '{"codigo":"ln_passo12_explique","mensagens":[{"tipo":"texto","texto":"Pode me explicar melhor a sua situação de prazo?"}],"aguarda_resposta":true,"tipo_resposta":"texto_livre","proximo_codigo":"ln_passo13","kanban_subetapa":"faixa_divida"}'::jsonb, 'urgencia_detalhe');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 17, 'mensagem_sequencial', '{"codigo":"ln_passo13","mensagens":[{"tipo":"texto","texto":"Vejo que não tem tempo sobrando, o prazo normal para o resultado é de 7 a 45 dias úteis mas depende de um processo judicial, portanto pode variar. Entender que, quanto antes der entrada mais rápido sai o resultado, pode ajudar na sua situação..."}],"aguarda_resposta":false,"proximo_codigo":"ln_passo14","kanban_subetapa":"faixa_divida"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 18, 'pergunta_checkpoint', '{"codigo":"ln_passo14","mensagens":[{"tipo":"texto","texto":"📌 Nós recebemos alguns vouchers da Associação que nos permitem oferecer uma condição especial muito expressiva. Como são limitados, para liberar a proposta com a melhor condição possível, precisamos saber:\n\n👉 *É prioridade para você já entrar com o CPF para ser limpo e começar a contar o prazo hoje?*\n1️⃣ Sim\n2️⃣ Não"}],"aguarda_resposta":true,"tipo_resposta":"menu","opcoes":[{"valor":"sim","rotulos":["1","1️⃣","sim"],"proximo_codigo":"ln_passo15_router"},{"valor":"nao","rotulos":["2","2️⃣","nao"],"proximo_codigo":"ln_passo15_router"}],"kanban_subetapa":"faixa_divida"}'::jsonb, 'prioridade_fechar_hoje');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 19, 'condicional', '{"codigo":"ln_passo15_router","mensagens":[],"aguarda_resposta":false,"proximo_por_dado":{"campo":"alto_valor","se_igual":"sim","entao":"ln_passo15_alto_valor","senao":"ln_passo15_normal"},"kanban_subetapa":"envio_proposta"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 20, 'pergunta_checkpoint', '{"codigo":"ln_passo15_normal","mensagens":[{"tipo":"texto","texto":"(proposta calculada dinamicamente pela faixa de preço)"}],"aguarda_resposta":true,"tipo_resposta":"menu","opcoes":[{"valor":"avista","rotulos":["avista","a vista","à vista"],"proximo_codigo":"ln_passo16_1"},{"valor":"parcelado","rotulos":["parcelado","parcela"],"proximo_codigo":"ln_passo16_1"}],"kanban_subetapa":"envio_proposta"}'::jsonb, 'forma_pagamento');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 21, 'pergunta_checkpoint', '{"codigo":"ln_passo15_alto_valor","mensagens":[{"tipo":"texto","texto":"(qualificação de alto valor gerada dinamicamente)"}],"aguarda_resposta":true,"tipo_resposta":"menu","opcoes":[{"valor":"call","rotulos":["1","1️⃣"],"proximo_codigo":"ln_call_agendada"},{"valor":"whatsapp","rotulos":["2","2️⃣"],"proximo_codigo":"ln_passo15_selfservice"}],"kanban_subetapa":"envio_proposta"}'::jsonb, 'aceitou_call');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 22, 'mensagem_sequencial', '{"codigo":"ln_call_agendada","mensagens":[{"tipo":"texto","texto":"Combinado! Já vou avisar nosso especialista pra entrar em contato com você e agendar a ligação. 🙋‍♂️"}],"aguarda_resposta":false,"encerramento":{"sob_supervisor":true},"kanban_subetapa":"negociacao_duvidas"}'::jsonb, null);
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 23, 'pergunta_checkpoint', '{"codigo":"ln_passo15_selfservice","mensagens":[{"tipo":"texto","texto":"(proposta self-service de alto valor gerada dinamicamente)"}],"aguarda_resposta":true,"tipo_resposta":"menu","opcoes":[{"valor":"avista","rotulos":["avista","a vista","à vista"],"proximo_codigo":"ln_passo16_1"},{"valor":"parcelado","rotulos":["parcelado","parcela"],"proximo_codigo":"ln_passo16_1"}],"kanban_subetapa":"envio_proposta"}'::jsonb, 'forma_pagamento');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 24, 'pergunta_checkpoint', '{"codigo":"ln_passo16_1","mensagens":[{"tipo":"texto","texto":"Perfeito! Só preciso confirmar uma coisa: qual a melhor data pra você pra realizar o pagamento da primeira parcela? O processo só dá entrada depois que o pagamento for confirmado, viu?"}],"aguarda_resposta":true,"tipo_resposta":"texto_livre","proximo_codigo":"ln_passo17a","kanban_subetapa":"negociacao_duvidas"}'::jsonb, 'data_primeira_parcela');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 25, 'pergunta_checkpoint', '{"codigo":"ln_passo17a","mensagens":[{"tipo":"texto","texto":"👍 Entendido! Agora vou enviar os dados necessários para a emissão do contrato, em 2 minutinhos vc consegue preencher:"},{"tipo":"texto","texto":"📌 *DADOS PARA LIMPEZA DE NOME:*\n\nCPF:\nNome Completo:"}],"aguarda_resposta":true,"tipo_resposta":"texto_livre","proximo_codigo":"ln_passo17b","kanban_subetapa":"dados_contrato"}'::jsonb, 'dados_pessoa_limpar');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 26, 'pergunta_checkpoint', '{"codigo":"ln_passo17b","mensagens":[{"tipo":"texto","texto":"📌 *DADOS DE QUEM VAI ASSINAR CONTRATO:*\n\n** CPF:\n** Nome Completo:\n** RG:\n** Estado Civil:\n** Profissão:\n** Nacionalidade:\n** Data Nascimento:\n** E-mail:\n** Whatsapp:\n** Endereço completo com cep:"}],"aguarda_resposta":true,"tipo_resposta":"texto_livre","proximo_codigo":"ln_passo18","kanban_subetapa":"dados_contrato"}'::jsonb, 'dados_assinante');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 27, 'pergunta_checkpoint', '{"codigo":"ln_passo18","mensagens":[{"tipo":"texto","texto":"Estamos quase concluindo! Agora falta somente a foto ou PDF de um documento válido (RG ou CNH) + comprovante de residência da pessoa que vai assinar o contrato. (se não tiver em mãos para enviar neste momento, me avise que anotamos aqui para você enviar depois.)"}],"aguarda_resposta":true,"tipo_resposta":"texto_livre","proximo_codigo":"ln_encerramento","kanban_subetapa":"dados_contrato"}'::jsonb, 'documentos_status');
insert into etapas_fluxo (fluxo_id, ordem, tipo_etapa, conteudo, campo_salvo) values ('7e410b97-3cc1-4118-bdfe-5ac9e3dedf62', 28, 'mensagem_sequencial', '{"codigo":"ln_encerramento","mensagens":[{"tipo":"texto","texto":"😊 Perfeito! Já anotei tudo aqui. Nossa equipe vai preparar seu contrato e te aviso por aqui assim que estiver tudo pronto pra você assinar. Muito obrigada pela confiança! 🙌"}],"aguarda_resposta":false,"encerramento":{"sob_supervisor":true},"kanban_subetapa":"dados_contrato"}'::jsonb, null);

-- FAQs (FAQ_LIMPANOME_SERASA_SPC.md)
insert into faqs (produto_id, pergunta, resposta) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'É certeza que vou conseguir aprovação de crédito após limpar meu nome?', 'A maioria dos clientes consegue aprovação de crédito/financiamento algumas semanas após a conclusão do processo, mas lojas e principalmente instituições financeiras usam outros critérios além do nome limpo para aprovar crédito — nome limpo não é garantia de aprovação.

A única certeza absoluta: solicitar crédito com nome sujo (situação atual) será negado. A ArrudaCred não controla a avaliação de crédito de terceiros, então não garante aprovação — o que ela garante em contrato é a remoção das restrições no SERASA, SPC Brasil, SPC Boa Vista e CENPROT.');
insert into faqs (produto_id, pergunta, resposta) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'O score vai aumentar depois de limpar o nome?', 'Score é o resultado de um cálculo matemático sobre a situação financeira: restrição = score baixo; nome limpo = tendência de melhora. Sim, o score vai melhorar conforme as dívidas são pagas ou as restrições removidas — de forma gradativa. Exceção: se o cliente tiver contas do mês atual atrasadas/vencidas, o score pode ficar travado ou até cair.');
insert into faqs (produto_id, pergunta, resposta) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'Quando e quanto o score aumenta?', 'Não é possível precisar quanto nem quando — depende do algoritmo do Serasa (hoje usa IA e muda constantemente). Regra geral: se o CPF não tiver contas atrasadas nos últimos 30 dias, já sobe um pouco de cara. O aumento mais relevante é gradativo ao longo dos próximos 90 dias, desde que o cliente mantenha hábitos de bom pagador e poucas consultas no nome.');
insert into faqs (produto_id, pergunta, resposta) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'As restrições podem voltar? O que é o seguro-garantia?', 'O processo é judicial, então é normal os órgãos de proteção ao crédito apresentarem recursos ao longo do tempo — isso pode fazer restrições voltarem (parcial ou totalmente). Não é falha no serviço, é andamento normal do processo.

Seguro-garantia de 12 meses incluso no valor da contratação cobre: reinserção parcial das restrições, reinserção total das restrições, inserção de restrição nova referente a nova dívida.

Acionamento do seguro: a associação entra com novo pedido de remoção, conforme regras do contrato. Taxa de R$ 250,00 por CPF/CNPJ, cobrada sempre que o seguro for acionado.');
insert into faqs (produto_id, pergunta, resposta) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'Qual a diferença entre restrição e dívida?', 'Restrição = anotação negativa referente à dívida que prejudica o nome — a ArrudaCred consegue baixar isso via ação judicial com base no Decreto nº 2.181/97 (art. 13, incisos XIII e XIV), no art. 42 do Código de Defesa do Consumidor e na Súmula 359 do STJ.

Dívida = continua existindo internamente na loja/banco onde foi contraída (e no Banco Central) — o cliente pode negociar isso depois, quando tiver fôlego financeiro ou achar melhor.');
insert into faqs (produto_id, pergunta, resposta) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'Posso resolver o BACEN/SCR/CCF junto com a Limpeza de Nome Serasa/SPC?', '*Bacen depois da proposta Limpa Nome SERASA/SPC!!*

Para dar entrada na ação de atualização do Registrato SCR (Banco Central - BACEN) removendo anotações negativas na coluna "VENCIDOS", é necessário estar com nome limpo no SERASA, SPC Brasil, SCPC Boa Vista e CENPROT já que isso faz parte da defesa utilizado no processo.

O caminho é realizar primeiro as baixas nas restrições Serasa/SPC para na sequência, tirar um relatório atualizado do SCR e aí sim, orçar e contratar o serviço correspondente no BACEN, ok?');
insert into faqs (produto_id, pergunta, resposta) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'Quais as garantias que eu tenho contratando a ArrudaCred?', 'Essa é uma ótima pergunta, e eu também faria essa pergunta no seu lugar. 😊

A sua principal garantia é que você está contratando uma empresa com anos de atuação, milhares de clientes atendidos, excelente reputação no Google e no Reclame Aqui, além de um contrato formal de prestação de serviços.

Além disso, nosso contrato prevê que, caso não consigamos entregar o serviço dentro do prazo máximo contratado, você tem direito ao reembolso previsto contratualmente.');
insert into faqs (produto_id, pergunta, resposta) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'Posso ver uma minuta do contrato?', 'Claro! 😊 Antes da assinatura você receberá o contrato completo para analisar com calma. Como ele é elaborado com os dados do cliente e do serviço contratado, não trabalhamos com uma minuta padrão. Se surgir qualquer dúvida, faço questão de explicar cada cláusula antes da assinatura.');
insert into faqs (produto_id, pergunta, resposta) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'Como funciona o processo de limpeza de nome?', 'A limpeza de nome é realizada por meio de uma ação judicial coletiva, promovida por associações de defesa dos direitos do consumidor, com fundamento no Decreto nº 2.181/97 (art. 13, incisos XIII e XIV), no art. 42 do Código de Defesa do Consumidor e na Súmula 359 do Superior Tribunal de Justiça (STJ). O objetivo da ação é buscar a remoção das restrições dos órgãos de proteção ao crédito, sem quitar ou extinguir as dívidas, que continuam existindo normalmente.

Por envolver uma ação coletiva e dados pessoais sensíveis dos associados (como documentos, informações financeiras e registros de dívidas), o processo tramita sob segredo de justiça, conforme a legislação aplicável. Por esse motivo, não é permitido divulgar o número do processo, fornecer cópias dos autos, decisões judiciais ou permitir consulta às peças processuais, preservando a privacidade e a segurança de todos os participantes.

Após a contratação, nossa equipe acompanha todo o processo até a conclusão e mantém você informado durante as etapas do serviço.');
insert into faqs (produto_id, pergunta, resposta) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'Existe chance das restrições voltarem?', 'Sim, essa possibilidade existe. 😊

Como a remoção das restrições ocorre por meio de uma ação judicial, é perfeitamente normal que, ao longo do processo, os órgãos de proteção ao crédito apresentem recursos ou outras manifestações processuais. Em alguns casos, isso pode fazer com que as restrições voltem a aparecer, parcial ou totalmente.

Isso não significa que houve falha no serviço, mas sim que faz parte do andamento normal de um processo judicial. Pensando nisso, a ArrudaCred oferece uma solução específica para proporcionar ainda mais tranquilidade ao cliente, conforme as condições previstas em contrato.');

-- Preços por faixa (SCRIPT_LIMPANOME_SERASA_SPC.md)
insert into precos_por_faixa (produto_id, faixa_min, faixa_max, preco_cheio, preco_avista, parcelas_boleto_qtd, parcelas_boleto_valor, parcelas_cartao_max, voucher_avista, voucher_parcelas_qtd, voucher_parcelas_valor) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 3000, 10000, 2580, 1290, 6, 430, 12, 899, 6, 299);
insert into precos_por_faixa (produto_id, faixa_min, faixa_max, preco_cheio, preco_avista, parcelas_boleto_qtd, parcelas_boleto_valor, parcelas_cartao_max, voucher_avista, voucher_parcelas_qtd, voucher_parcelas_valor) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 10000, 30000, 3600, 1800, 6, 600, 12, 1290, 6, 399);
insert into precos_por_faixa (produto_id, faixa_min, faixa_max, preco_cheio, preco_avista, parcelas_boleto_qtd, parcelas_boleto_valor, parcelas_cartao_max, voucher_avista, voucher_parcelas_qtd, voucher_parcelas_valor) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 30000, 50000, 3600, 1800, 6, 600, 12, 1290, 6, 399);
insert into precos_por_faixa (produto_id, faixa_min, faixa_max, preco_cheio, preco_avista, parcelas_boleto_qtd, parcelas_boleto_valor, parcelas_cartao_max, voucher_avista, voucher_parcelas_qtd, voucher_parcelas_valor) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 50000, 100000, 4800, 2400, 6, 800, 12, 1790, 6, 599);
insert into precos_por_faixa (produto_id, faixa_min, faixa_max, preco_cheio, preco_avista, parcelas_boleto_qtd, parcelas_boleto_valor, parcelas_cartao_max, voucher_avista, voucher_parcelas_qtd, voucher_parcelas_valor) values ('aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 100000, 500000, 6000, 3000, 6, 1000, 12, 2390, 6, 799);

-- Valores configuráveis (PLANO_MESTRE seção 8.9 / MODELAGEM_DADOS seção "Valores Configuráveis")
insert into configuracoes (unidade_negocio_id, produto_id, chave, valor, descricao) values ('931a408d-0c7a-4d88-ab07-49a3b46f0eb4', 'aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'limpanome_investimento_minimo_avista', '899'::jsonb, 'Investimento mínimo à vista para restrição abaixo de R$3 mil (Passo 7 do script) — usado quando o valor não cabe na tabela por faixa.');
insert into configuracoes (unidade_negocio_id, produto_id, chave, valor, descricao) values ('931a408d-0c7a-4d88-ab07-49a3b46f0eb4', 'aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'limpanome_investimento_minimo_parcelado', '{"qtd":6,"valor":299}'::jsonb, 'Parcelamento do investimento mínimo (Passo 7) — mesma regra do valor à vista acima.');
insert into configuracoes (unidade_negocio_id, produto_id, chave, valor, descricao) values ('931a408d-0c7a-4d88-ab07-49a3b46f0eb4', 'aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'limpanome_formula_alto_valor', '{"valor_fixo":7680,"percentual":0.015}'::jsonb, 'Fórmula de previsibilidade de receita para restrições acima do corte de alto valor: valor_fixo + percentual × valor da restrição (KANBAN_COMERCIAL_LIMPANOME.md).');
insert into configuracoes (unidade_negocio_id, produto_id, chave, valor, descricao) values ('931a408d-0c7a-4d88-ab07-49a3b46f0eb4', 'aaf16cb9-ba7a-43c6-b1a6-ce4d4202824f', 'limpanome_corte_alto_valor', '500000'::jsonb, 'A partir deste valor de restrição, a Malala qualifica e tenta agendar call com Luiz em vez de propor direto (PLANO_MESTRE seção 8.7).');

-- Agenda padrão de follow-up (SCRIPT_LIMPANOME_SERASA_SPC.md, premissas gerais)
insert into agendas_followup (id, nome) values ('90a7dd7d-7ded-437a-a1e3-08bc827486bb', 'Padrão');
insert into agenda_itens (agenda_id, ordem, intervalo_valor, intervalo_unidade, canal, respeita_janela_comercial, conteudo) values ('90a7dd7d-7ded-437a-a1e3-08bc827486bb', 1, 10, 'minutos', 'whatsapp', false, '🙋‍♂️🙋‍♂️ [Primeiro_Nome] ??');
insert into agenda_itens (agenda_id, ordem, intervalo_valor, intervalo_unidade, canal, respeita_janela_comercial, conteudo) values ('90a7dd7d-7ded-437a-a1e3-08bc827486bb', 2, 45, 'minutos', 'whatsapp', true, '👀 Oi, está por aí ainda? conseguiu ver minha mensagem?');
insert into agenda_itens (agenda_id, ordem, intervalo_valor, intervalo_unidade, canal, respeita_janela_comercial, conteudo) values ('90a7dd7d-7ded-437a-a1e3-08bc827486bb', 3, 4, 'horas', 'whatsapp', true, '👋 Lembrando: estou por aqui te aguardando...');
insert into agenda_itens (agenda_id, ordem, intervalo_valor, intervalo_unidade, canal, respeita_janela_comercial, conteudo) values ('90a7dd7d-7ded-437a-a1e3-08bc827486bb', 4, 24, 'horas', 'whatsapp', true, '🙂 [Primeiro_Nome], sei que nem sempre é o melhor momento para falar, caso você tenha decidido não continuar com este atendimento, basta me dizer que encerro agora, ok?');
insert into agenda_itens (agenda_id, ordem, intervalo_valor, intervalo_unidade, canal, respeita_janela_comercial, conteudo) values ('90a7dd7d-7ded-437a-a1e3-08bc827486bb', 5, 3, 'dias', 'whatsapp', true, '📌 Como você não respondeu nada, vou tentar mais uma vez: você ainda tem interesse em continuar este atendimento? Se não tiver, por gentileza me informe...');
insert into agenda_itens (agenda_id, ordem, intervalo_valor, intervalo_unidade, canal, respeita_janela_comercial, conteudo) values ('90a7dd7d-7ded-437a-a1e3-08bc827486bb', 6, 7, 'dias', 'whatsapp', true, '🔔 Última tentativa de contato: Você está por aí?');
insert into agenda_itens (agenda_id, ordem, intervalo_valor, intervalo_unidade, canal, respeita_janela_comercial, conteudo) values ('90a7dd7d-7ded-437a-a1e3-08bc827486bb', 7, 10, 'dias', 'whatsapp', true, '⛔ Este atendimento foi encerrado automaticamente devido falta de resposta. Se precisar, você pode chamar novamente a qualquer momento... Até mais!');
insert into agenda_itens (agenda_id, ordem, intervalo_valor, intervalo_unidade, canal, respeita_janela_comercial, conteudo) values ('90a7dd7d-7ded-437a-a1e3-08bc827486bb', 8, 30, 'dias', 'email', true, 'Nutrição 1 — reengajamento educativo (riscos de nome negativado)');
insert into agenda_itens (agenda_id, ordem, intervalo_valor, intervalo_unidade, canal, respeita_janela_comercial, conteudo) values ('90a7dd7d-7ded-437a-a1e3-08bc827486bb', 9, 60, 'dias', 'email', true, 'Nutrição 2 — reengajamento educativo (nem todo acordo limpa o nome de verdade)');
insert into agenda_itens (agenda_id, ordem, intervalo_valor, intervalo_unidade, canal, respeita_janela_comercial, conteudo) values ('90a7dd7d-7ded-437a-a1e3-08bc827486bb', 10, 90, 'dias', 'email', true, 'Nutrição 3 — última tentativa de reativação');
